### ISSUE TITLE
Setup CI jobs

### ISSUE THREAD

**Issue by PiotrekDlang** [JinShil/utiliD#2]
Main goal:
- testing and verifying new PRs

First Platform to support
- Linux x86_64 

First Deadline :) :
- 2019-05-18

**Comment by JinShil** [comment]
I watched this video here (https://www.youtube.com/watch?v=vlBuNM6Wzic) to see what could be done with Azure Pipelines.  According to the video I had to have a Microsoft Account and I had to give access to this repository, and I think that is something only I could do, so I did it.

I think we just need to add a unit test, create a build script (in D of course), and then modify the .yml file to have Azure Pipelines run the build script.   The build script should both build the library and run the unittests.  I'm new to this so still figuring some things out.

**Comment by JinShil** [comment]
Of course, we could also use some code to build :blush:

**Comment by PiotrekDlang** [comment]
OK. I will look into this.

Also there is an alternative to use Gitlab pipline (I wanted to try this):
https://dev.to/anoff/gitlab-cicd-for-githubhow-and-why-4bik

The free account plan gives:
"2,000 CI pipeline minutes per group per month on our shared runners"

**Comment by JinShil** [comment]
> Also there is an alternative to use Gitlab pipline (I wanted to try this):

I don't see any reason we can't try both.  Maybe over time we'll choose one or the other, or maybe we can leverage both for different kinds of tests or different platforms.

**Comment by PiotrekDlang** [comment]
It seems Azure Pipeline service is unlimited for public repository. For me it's OK to start with Azure.
It may a little problem that I don't know how to test it as I don't have Microsoft account.

I opened PR to test CI behavior. You may comment your finding there. I will also analyze Azure piplines.

**Comment by Basile-z** [comment]
Take care with Azure Pipelines, they tend to block personal accounts with no real reasons.

**Comment by PiotrekDlang** [comment]
@Basile-z Can you provide a reference for more details?

**Comment by Basile-z** [comment]
When you think it's cool, after a few weeks you have to do [this](https://github.com/Basile-z/styx/commit/8db80d373ff197d5910ab975366b56fb521b74e2).

**Comment by Basile-z** [comment]
they block you until or unless you gives more personal info. Pretty much the same strategy as tweeter.

**Comment by PiotrekDlang** [comment]
@Basile-z thanks for the info. I will keep that in mind and check other alternatives in case Azure pipelines won't work

**Comment by JinShil** [comment]
I consider this issue resolved.  There's still much more work to do on CIs, but this first step is finished.

**Comment by JinShil** [comment]
https://github.com/JinShil/utiliD/pull/3
